[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool]
  [tool.commitizen]
  version = "0.1.2"
  version_files = [
    "pyproject.toml:version",
    "README.md:pre-commit-action@"
  ]

  [tool.poetry]
  name = "pre-commit-action"
  version = "0.1.2"
  description = "Optimized GitHub Action for Running pre-commit Hooks"
  authors = ["Kurt von Laven <kurt.von.laven@gmail.com>"]
  license = "MIT"

  [tool.poetry.dependencies]
  python = "^3.10.4"

  [tool.poetry.dev-dependencies]
  commitizen = "^2.24.0"
  pre-commit = "^2.18.1"
